=== YeseniaCam/StoryBoard/xml/storyboarduserschema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="Usuarios">
		<xs:complexType>
			<xs:sequence>				
				<xs:element name="Usuario" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Nombre" type="xs:string"/>
							<xs:element name="Correo" type="xs:string"/>
							<xs:element name="Username" type="xs:string"/>
							<xs:element name="Password" type="xs:string"/>
							<xs:element name="Tipo" type="xs:string"/>
							<xs:element name="Grupo" type="xs:string" minOccurs="0" maxOccurs="1" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>						
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== YeseniaCam/StoryBoard/xml/Usuarios.xml
<?xml version="1.0" encoding="UTF-8"?>
<Usuarios xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="storyboarduserschema.xsd">
    
    <Usuario>
    	<Nombre>Profesor</Nombre>
    	<Correo>Prof@gmail.com</Correo>
    	<Username>Profesor</Username>
    	<Password>1234</Password>
    	<Tipo>Profesor</Tipo>
    </Usuario>
    
    <Usuario>
    	<Nombre>Admin</Nombre>
    	<Correo>Prof@gmail.com</Correo>
    	<Username>Administrador</Username>
    	<Password>1234</Password>
    	<Tipo>Administrador</Tipo>
    </Usuario>
    
<Usuario><Nombre>Alumno</Nombre><Correo>alumno@alumno.com</Correo><Username>Alumno</Username><Password>1234</Password><Tipo>Estudiante</Tipo><Grupo>3CM9</Grupo></Usuario></Usuarios>
